### ISSUE TITLE
Background image + background-color causes mobile scroll bar hard to see on ios

### ISSUE THREAD

**Issue by Cogito** [LukeNZ/spacex-reddit-css#2]
The background-color for the <body> element is set to $white, which means the ios scrollbar is styled to be a dark grey.

This scrollbar is almost impossible to see against the background image that is being used.

I would suggest using the same background-color as the sidebar, #374148 (which isn't in _design.scss as far as I can tell), but I don't know if this will be dark enough to make the contrast between the scrollbar and the background image strong enough.

**Comment by LukeNZ** [comment]
Do you mean for the root `html` element? If so, yep, I have been meaning to set the background-color on that to something closer to the image. I'll get this changed tonight. Cheers!

**Comment by LukeNZ** [comment]
So I've taken a look at this, and even a purely black webpage doesn't seem to render the iOS scrollbar in a different color. I've changed the `background-color` for `html` to be `$lightslate` for now.

**Comment by LukeNZ** [comment]
Closing #2. If this is still an issue, please reraise it here and we can discuss.
